### ISSUE TITLE
Closed form solution for M in point to point method

### ISSUE THREAD

**Issue by GavinBarill** [alecjacobson/geometry-processing-registration#18]
In this formula for M, both matrices for P and X are k by 3, so would result in a k by k matrix for M. I've found that X^T * P works instead.

<img width="79" alt="screen shot 2018-02-03 at 8 16 53 pm" src="https://user-images.githubusercontent.com/9832231/35773720-f3d2fb32-0927-11e8-8d43-315d2a51b435.png">

**Comment by alecjacobson** [comment]
Thanks for the correction.

As established earlier in the README.md, the Frobenius inner product has the property that:

```
<A,BC> = <B^TA,C>
```

Replacing `A,B,C` with `P,X,R^T`, we have

```
<P,XR^T> = <X^TP,R^T>
```

Frobenius inner product is also invariant to transposes: `<A,B> = <A^T,B^T>`, so we can transpose every term:

```
<P^T,RX^T> = <P^TX,R>
```

And finally inner product is symmetric: `<A,B> = <B,A>`:

```
<RX^T,P^T> = <R,P^TX>
```

So the correction should be:

```
M = P^T X
```
