### ISSUE TITLE
Correction for Point to Plane

### ISSUE THREAD

**Issue by MianWei8** [alecjacobson/geometry-processing-registration#21]
Given this pdf https://igl.ethz.ch/projects/ARAP/svd_rot.pdf I think that we should be using the transpose of the skew-symmetric matrix in the linearization of R since the closest rotation is V(Omega)U^T, not U(Omega)V^T. If we use the latter, we just need to transpose M.

**Comment by alecjacobson** [comment]
I think there's a transpose bug in the README after the line "taking advantage of the associativity property of the Frobenius norm:". The `<R^T,M>` should be `<R,M>` and this trickles through the following SVD.

**Comment by alecjacobson** [comment]
I pushed a correction. (The result is unchanged: in our notation the optimal rotation is indeed `U Ω V^T`.
