### ISSUE TITLE
LaTeX in README not rendering

### ISSUE THREAD

**Issue by juliagilenko** [alecjacobson/geometry-processing-registration#34]
I forked and cloned the repo, but when I open README.html, the LaTeX isn't rendered. Not sure if I've done something wrong on my end.

**Comment by alecjacobson** [comment]
Are you sure that you did a recursive clone? `git clone --recursive ...` ?

Just in case you might issue:

     git submodule update --init --recursive

**Comment by juliagilenko** [comment]
Whoops, I forgot it needs to be recursive. That was silly. Thanks!
